[package]
name = "urban-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.6", features = ["cargo"] }
full_moon = "0.17"
phf = { version = "0.11", features = ["macros"] }

[[bin]]
name = "urban"
path = "src/main.rs"
