instructions = [
    {"name": "not", "registers": 2, "number-arg": False},
    {"name": "add", "registers": 3, "number-arg": False},
    {"name": "add", "registers": 2, "number-arg": True},
    {"name": "sub", "registers": 3, "number-arg": False},
    {"name": "sub", "registers": 2, "number-arg": True},
    {"name": "mul", "registers": 3, "number-arg": False},
    {"name": "mul", "registers": 2, "number-arg": True},
    {"name": "div", "registers": 3, "number-arg": False},
    {"name": "div", "registers": 2, "number-arg": True},
    {"name": "adds", "registers": 3, "number-arg": False},
    {"name": "adds", "registers": 2, "number-arg": True},
    {"name": "subs", "registers": 3, "number-arg": False},
    {"name": "subs", "registers": 2, "number-arg": True},
    {"name": "muls", "registers": 3, "number-arg": False},
    {"name": "muls", "registers": 2, "number-arg": True},
    {"name": "divs", "registers": 3, "number-arg": False},
    {"name": "divs", "registers": 2, "number-arg": True},
    {"name": "addf", "registers": 3, "number-arg": False},
    {"name": "subf", "registers": 3, "number-arg": False},
    {"name": "mulf", "registers": 3, "number-arg": False},
    {"name": "divf", "registers": 3, "number-arg": False},
    {"name": "and", "registers": 3, "number-arg": False},
    {"name": "or", "registers": 3, "number-arg": False},
    {"name": "xor", "registers": 3, "number-arg": False},
    {"name": "shl", "registers": 2, "number-arg": True},
    {"name": "shr", "registers": 2, "number-arg": True},
    {"name": "shrs", "registers": 2, "number-arg": True},
    {"name": "ldr", "registers": 2, "number-arg": False},
    {"name": "ldr", "registers": 1, "number-arg": True},
    {"name": "str", "registers": 2, "number-arg": False},
    {"name": "str", "registers": 1, "number-arg": True},
    {"name": "mov", "registers": 2, "number-arg": False},
    {"name": "mov", "registers": 1, "number-arg": True},
    {"name": "movs", "registers": 1, "number-arg": True},
    {"name": "br", "registers": 1, "number-arg": False},
    {"name": "b", "registers": 0, "number-arg": True},
    {"name": "brl", "registers": 1, "number-arg": False},
    {"name": "bl", "registers": 0, "number-arg": True},
    {"name": "b.eq", "registers": 1, "number-arg": True},
    {"name": "b.ne", "registers": 1, "number-arg": True},
    {"name": "b.lt", "registers": 1, "number-arg": True},
    {"name": "b.gt", "registers": 1, "number-arg": True},
    {"name": "b.le", "registers": 1, "number-arg": True},
    {"name": "b.ge", "registers": 1, "number-arg": True},
    {"name": "nop", "registers": 0, "number-arg": False},
    {"name": "halt", "registers": 0, "number-arg": False},
    {"name": "interrupt", "registers": 0, "number-arg": True},
]


def mapped():
    res = sorted(instructions, key=lambda it: it["name"])
    for i, elem in enumerate(res):
        elem["index"] = i
    return res
