interrupts = ["read", "write"]


def write(out):
    print(
        """
// This file is automatically generated.
// It is not intended for manual editing.

//! This module contains constants for all interrupts
    """.strip(),
        file=out,
    )
    print(file=out)
    for i, interrupt in enumerate(interrupts):
        print(f"pub const INT_{interrupt.upper()}: u16 = {i};", file=out)
